version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:5.0
    ports:
      - "27018:27017"
    env_file:
      - .env    
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /mnt/db:/data/db
    networks:
      - mongo-net

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "7000:7000"
    depends_on:
      - mongo
    networks:
      -  mongo-net
    env_file:
      - .env  
    volumes:
      - type: bind
        source: ./backend
        target: /app
    working_dir: /app

  

  telegram:
    container_name: telegram
    image: telegram
    build:
      context: ./Telegram
      dockerfile: Dockerfile.dev
    ports:
      - "7004:7004"
    depends_on:
      - mongo
      - backend
    networks:
      - mongo-net
    env_file:
      - .env 
    volumes:
      - type: bind
        source: ./Telegram
        target: /app
    working_dir: /app  



networks:
  mongo-net:
