version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:5.0
    ports:
      - "27018:27017"
    env_file:
      - .env    
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /mnt/data/db:/data/db
    networks:
      - mongo-net

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - mongo
    networks:
      - mongo-net
    env_file:
      - .env  


  telegram:
    container_name: telegram
    image: telegram
    build:
      context: ./Telegram
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - mongo
      - backend
    networks:
      - mongo-net
    env_file:
      - .env 

  ussd:
    container_name: ussd
    image: ussd
    build:
      context: ./USSD
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - backend
    networks:
      - mongo-net
    env_file:
      - .env 



networks:
  mongo-net: