FROM node:16

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json .
RUN npm install
RUN npm install -g nodemon

# Bundle app source
COPY . .
EXPOSE 7004


CMD [ "nodemon", "server.js" ]

