name: CICD pipeline for the insuarance 
on:
  push:
      branches:
        - "main" 
jobs:
  provision:
    name: Run Ansible
    runs-on: ubuntu-latest
    steps:      
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install ansible
    - name: Add hosts to known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
             
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -f inventory.ini > known_hosts
        cat known_hosts >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: Run ansible playbook
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock              
      run: |
           echo MONGODB_CONNSTRING="${{secrets.MONGODB_CONNSTRING}}" >> .env
           echo MONGO_INITDB_DATABASE="${{secrets.MONGO_INITDB_DATABASE}}" >> .env
           echo MONGO_INITDB_ROOT_PASSWORD="${{secrets.MONGO_INITDB_ROOT_PASSWORD}}" >> .env
           echo MONGO_INITDB_ROOT_USERNAME="${{secrets.MONGO_INITDB_ROOT_USERNAME}}" >> .env
           echo AFRICAS_TALKING_API_KEY="${{secrets.AFRICAS_TALKING_API_KEY}}" >> .env
           echo CLAIMS_URL="${{secrets.CLAIMS_URL}}" >> .env
           echo USERS_URL="${{secrets.USERS_URL}}" >> .env
           echo BACKEND_SERVICE_PORT="${{secrets.BACKEND_SERVICE_PORT}}" >> .env
           echo TELEGRAM_SERVICE_PORT="${{secrets.TELEGRAM_SERVICE_PORT}}" >> .env
           echo TELEGRAM_API="${{secrets.TELEGRAM_API}}" >> .env
           echo CALLBACK_URL="${{secrets.CALLBACK_URL}}" >> .env
           echo OPENAI_API_KEY="${{secrets.OPENAI_API_KEY}}" >> .env
           ansible-playbook playbook.yml -u root --private-key="${{ secrets.SSH_PRIVATE_KEY }}" -i inventory.ini -vvv 
